controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

helloworld:
    path: /helloworld
    controller: App\Controller\HelloWorldController::hello
